/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.projeto.view;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author joaom
 */
public class FrmMenu extends javax.swing.JFrame {
    
    public String usuarioLogado;

    /**
     * Creates new form FrmMenu
     */
    public FrmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuControleClientes = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menu_ControleFuncionarios = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        menuControleFornecedores = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        menuControleEstoque = new javax.swing.JMenuItem();
        menuConsultaProduto = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        menu_pdv = new javax.swing.JMenuItem();
        menu_posicao = new javax.swing.JMenuItem();
        menu_historico = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        menuTrocaUsuario = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();

        jMenu9.setText("File");
        jMenuBar3.add(jMenu9);

        jMenu10.setText("Edit");
        jMenuBar3.add(jMenu10);

        jMenu11.setText("File");
        jMenuBar4.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar4.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Usuário: ");

        lblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(0, 0, 204));
        lblUsuario.setText("João Marcos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addComponent(lblUsuario))
        );

        jDesktopPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(0, 492, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\clientes.png")); // NOI18N
        jMenu1.setText("Clientes");

        menuControleClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuControleClientes.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\novo.png")); // NOI18N
        menuControleClientes.setText("Controle de Clientes");
        menuControleClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuControleClientes);

        jMenuBar2.add(jMenu1);

        jMenu8.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\funcionarios.png")); // NOI18N
        jMenu8.setText("Funcionários");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        menu_ControleFuncionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_ControleFuncionarios.setText("Controle de Funcionários");
        menu_ControleFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ControleFuncionariosActionPerformed(evt);
            }
        });
        jMenu8.add(menu_ControleFuncionarios);

        jMenuBar2.add(jMenu8);

        jMenu13.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\fornecedores.png")); // NOI18N
        jMenu13.setText("Fornecedores");

        menuControleFornecedores.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuControleFornecedores.setText("Controle de Fornecedores");
        menuControleFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleFornecedoresActionPerformed(evt);
            }
        });
        jMenu13.add(menuControleFornecedores);

        jMenuBar2.add(jMenu13);

        jMenu14.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\produtos.png")); // NOI18N
        jMenu14.setText("Produtos");

        menuControleEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuControleEstoque.setText("Controle de Estoque");
        menuControleEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuControleEstoqueActionPerformed(evt);
            }
        });
        jMenu14.add(menuControleEstoque);

        menuConsultaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuConsultaProduto.setText("Consulta de Produtos");
        menuConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConsultaProdutoActionPerformed(evt);
            }
        });
        jMenu14.add(menuConsultaProduto);

        jMenuBar2.add(jMenu14);

        jMenu15.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\vendas.png")); // NOI18N
        jMenu15.setText("Vendas");

        menu_pdv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_pdv.setText("Abrir PDV");
        menu_pdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pdvActionPerformed(evt);
            }
        });
        jMenu15.add(menu_pdv);

        menu_posicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_posicao.setText("Posiçao do dia");
        menu_posicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_posicaoActionPerformed(evt);
            }
        });
        jMenu15.add(menu_posicao);

        menu_historico.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_historico.setText("Histórico de Vendas");
        menu_historico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_historicoActionPerformed(evt);
            }
        });
        jMenu15.add(menu_historico);

        jMenuBar2.add(jMenu15);

        jMenu16.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\configuracoes.png")); // NOI18N
        jMenu16.setText("Configurações");

        menuTrocaUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuTrocaUsuario.setText("Troca de Usuários");
        menuTrocaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrocaUsuarioActionPerformed(evt);
            }
        });
        jMenu16.add(menuTrocaUsuario);

        jMenuBar2.add(jMenu16);

        jMenu17.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaom\\OneDrive\\Documentos\\NetBeansProjects\\Projeto_Vendas\\src\\main\\java\\images\\sair.png")); // NOI18N
        jMenu17.setText("Sair");
        jMenu17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu17MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu17);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuControleClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleClientesActionPerformed
        Frmcliente tela = new Frmcliente();
                tela.setVisible(true);
    }//GEN-LAST:event_menuControleClientesActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Maximizando tela
        this.setExtendedState(this.MAXIMIZED_BOTH);
        lblUsuario.setText(usuarioLogado);
        this.setVisible(true);
    }//GEN-LAST:event_formWindowActivated

    private void menu_ControleFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ControleFuncionariosActionPerformed
          FrmFuncionarios tela = new FrmFuncionarios();
                tela.setVisible(true);
    }//GEN-LAST:event_menu_ControleFuncionariosActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
          FrmFuncionarios tela = new FrmFuncionarios();
                tela.setVisible(true);
    }//GEN-LAST:event_jMenu8ActionPerformed

    private void menuControleFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleFornecedoresActionPerformed
       FrmFornecedores tela = new FrmFornecedores();
                tela.setVisible(true);
    }//GEN-LAST:event_menuControleFornecedoresActionPerformed

    private void menuControleEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuControleEstoqueActionPerformed
       
    }//GEN-LAST:event_menuControleEstoqueActionPerformed

    private void menuConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaProdutoActionPerformed
                FrmProdutos tela = new FrmProdutos();
                tela.jTabbedPane1.setSelectedIndex(1);
                tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_menuConsultaProdutoActionPerformed

    private void menu_pdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pdvActionPerformed
         FrmPDV tela = new FrmPDV();
                tela.setVisible(true);
    }//GEN-LAST:event_menu_pdvActionPerformed

    private void menu_historicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_historicoActionPerformed
       FrmHistorico tela = new FrmHistorico();
                tela.setVisible(true);
    }//GEN-LAST:event_menu_historicoActionPerformed

    private void menu_posicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_posicaoActionPerformed
         FrmTotalVenda tela = new FrmTotalVenda();
                tela.setVisible(true);
    }//GEN-LAST:event_menu_posicaoActionPerformed

    private void menuTrocaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrocaUsuarioActionPerformed
        // Efetuar Logout
        
        FrmLogin telalogin = new FrmLogin();
        this.dispose();
        
        telalogin.setVisible(true);
        
    }//GEN-LAST:event_menuTrocaUsuarioActionPerformed

    private void jMenu17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu17MouseClicked
        // Sair do sistema
        
        int op;
        
        op = JOptionPane.showConfirmDialog(null,"Você tem certeza que deseja sair?");
        
        if(op == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenu17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    public javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuItem menuConsultaProduto;
    private javax.swing.JMenuItem menuControleClientes;
    private javax.swing.JMenuItem menuControleEstoque;
    private javax.swing.JMenuItem menuControleFornecedores;
    private javax.swing.JMenuItem menuTrocaUsuario;
    public javax.swing.JMenuItem menu_ControleFuncionarios;
    public javax.swing.JMenuItem menu_historico;
    private javax.swing.JMenuItem menu_pdv;
    public javax.swing.JMenuItem menu_posicao;
    // End of variables declaration//GEN-END:variables
}
